name: Linux (clang)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup required packages"
        run: sudo apt-get install -y binutils-dev libssl-dev uuid-dev

      - name: "Setup clang"
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 12
          rm llvm.sh

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        env:
          CMAKE_CXX_FLAGS: "-stdlib=libc++"
        run: |
          cd build
          ./unix.sh
